skytemple_files/hardcoded/fixed_floor.py
I have changed some things about fixed floors:
- I created an enumeration for enemy settings/monster spawn types, because there seems to be more types than just enemies/allies.
- The unknown boolean 10 in fixed floor properties determines if you automatically exit the floor when you defeat all the enemies on the floor (like in a boss fight).
- Some other minor fixes.
Pull request Skytemple/skytemple#58 must also be accepted to work.
=> Improving fixed floors and monster spawns types.

skytemple_files/compression/px/decompressor.py, skytemple_files/graphics/kao/model.py
Related to issue #31.
Does not fix that issue, but at least prevents the user from importing a portrait with a compressed size greater than 800 bytes.
It should always be checked, because you will never be sure that after compression the portrait will have less than 800 bytes.
=> Prevent importing a portrait with a too big compressed size

skytemple_files/graphics/bpc/model.py, skytemple_files/graphics/bpl/model.py, skytemple_files/graphics/bpl/writer.py
Adds dummy grayscale palette entries for map backgrounds when the palette file doesn't have enough palettes, and adds a getter and a setter to get/set those palettes without the dummy entries.
This must be combined with the pull request in SkyTemple/skytemple.
This should fix #11.
=> Fix map backgrounds rendered incorrectly

skytemple_files/_resources/ppmdu_config/pmd2dungeondata.xml, skytemple_files/common/types/file_types.py, skytemple_files/graphics/zmappat/__init__.py, skytemple_files/graphics/zmappat/dbg/export_test.py, skytemple_files/graphics/zmappat/dbg/import_test.py, skytemple_files/graphics/zmappat/handler.py, skytemple_files/graphics/zmappat/model.py, skytemple_files/graphics/zmappat/writer.py
The zmappat file is entry 1035 in the dungeon bin.
It contains the image tiles data used to render the mini-map in dungeons.
This pull request provides: 
- Support for reading/handling/writing zmappat files.
- Support for exporting zmappat file to image files.
- Support for importing zmappat file from image files.
=> Add primitive support for zmappat file

skytemple_files/common/types/file_types.py, skytemple_files/graphics/fonts/__init__.py, skytemple_files/graphics/fonts/abstract.py, skytemple_files/graphics/fonts/font_dat/dbg/export_test.py, skytemple_files/graphics/fonts/font_dat/dbg/import_test.py, skytemple_files/graphics/fonts/font_dat/handler.py, skytemple_files/graphics/fonts/font_dat/model.py, skytemple_files/graphics/fonts/font_dat/writer.py, skytemple_files/graphics/fonts/font_sir0/dbg/export_test.py, skytemple_files/graphics/fonts/font_sir0/dbg/import_test.py, skytemple_files/graphics/fonts/font_sir0/handler.py, skytemple_files/graphics/fonts/font_sir0/model.py, skytemple_files/graphics/fonts/font_sir0/writer.py
This adds basic support for editing raw data (files with "rd" at the end; only present and used in EU and US versions) and sir0 (present in all versions but only used in JP version) monochrome font files, including:
- reading, editing and writing files of those types;
- importing and exporting fonts as xml + image files; note that both font file types use the same format for importing and exporting, which make them nearly compatible (there are some properties that aren't the same in each, but default values are provided if they don't exist in the xml file).
=> Basic support for monochrome font files

skytemple_files/common/types/file_types.py, skytemple_files/graphics/fonts/abstract.py, skytemple_files/graphics/fonts/font_dat/__init__.py, skytemple_files/graphics/fonts/font_dat/model.py, skytemple_files/graphics/fonts/font_dat/writer.py, skytemple_files/graphics/fonts/font_sir0/__init__.py, skytemple_files/graphics/fonts/font_sir0/model.py, skytemple_files/graphics/fonts/font_sir0/writer.py, skytemple_files/graphics/fonts/graphic_font/__init__.py, skytemple_files/graphics/fonts/graphic_font/dbg/export_test.py, skytemple_files/graphics/fonts/graphic_font/dbg/import_test.py, skytemple_files/graphics/fonts/graphic_font/handler.py, skytemple_files/graphics/fonts/graphic_font/model.py, skytemple_files/graphics/fonts/graphic_font/writer.py, skytemple_files/graphics/pal/__init__.py, skytemple_files/graphics/pal/handler.py, skytemple_files/graphics/pal/model.py, skytemple_files/graphics/pal/writer.py
Adds basic support to edit graphic font files (button, Orb and TM icons, etc. / staff roll font): 
- import/export entries of those files;
- associate them with a palette file (".pal" files).
Also adds support to open/edit/write raw palette files (mainly ".pal" files), since graphic fonts use them.
=> Add support to edit graphic fonts

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/hardcoded/default_starters.py
Adds a module to read/write default starters species values.
Should fix #42.
=> Add support to edit default starters species

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_dungeon_data/eu/patch_available_items.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_dungeon_data/eu/patch_floor_ranks.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_dungeon_data/eu/patch_forbidden_floors.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_dungeon_data/na/patch_available_items.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_dungeon_data/na/patch_floor_ranks.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_dungeon_data/na/patch_forbidden_floors.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_dungeon_data/selector_arm9.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_item_lists/eu/patch.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_item_lists/na/patch.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/dungeon_data/floor_attribute/__init__.py, skytemple_files/dungeon_data/floor_attribute/handler.py, skytemple_files/dungeon_data/floor_attribute/model.py, skytemple_files/dungeon_data/floor_attribute/writer.py, skytemple_files/patch/handler/extract_dungeon_data.py, skytemple_files/patch/handler/extract_item_lists.py, skytemple_files/patch/patches.py
- Improve 'ExtractHardcodedItemLists' patch. 
- Add a patch to extract and edit rank and no mission floor attributes.
Note: there is also a 3rd data structure I extracted, but I was too lazy to add models for it; it is important though, as it breaks consistency with the dungeon floor data.
=> Add and Improve patches

skytemple_files/data/md/model.py, skytemple_files/data/md/writer.py
The HP regeneration value inside monster data should be unsigned, since the max value is 250.
=> Make HP regeneration unsigned

skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsEU.asm, skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsUS.asm, skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/completeteamcontrol.asm, skytemple_files/patch/handler/complete_team_control.py
Bugfix: the gusting wind counter would lower whenever you moved a partner in manual mode. Fixed it so it only lowers once per round as it's supposed to. Thanks to End and FireFox6 for finding it.
Also @End45 - the hack takes 0x420 bytes in the extra overlay now I swear I didn't make a weed joke on purpose
=> complete team control update to 1.2.1

skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsEU.asm, skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsUS.asm, skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/completeteamcontrol.asm, skytemple_files/patch/handler/complete_team_control.py
Fixed a bug with looking at a temporary party member's moves. You can now look at a temporary party member's moves as if it was a permanent party member.
=> updated CTC to 1.2.2

skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsEU.asm, skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsUS.asm, skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/completeteamcontrol.asm, skytemple_files/patch/handler/complete_team_control.py
This prevents players from selecting the quicksave option in the rest menu while they're controlling a partner, to prevent bugs. I can't believe I created CTC two years ago and didn't think about this until now.
@End45 the hack now needs 470h bytes
=> CTC updated to 1.2.3

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/common/patch.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/selector_overlay13.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/skip_quiz/common/patch.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/skip_quiz/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/skip_quiz/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/skip_quiz/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/skip_quiz/selector_overlay13.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/common/i18n_util.py, skytemple_files/patch/handler/choose_starter.py, skytemple_files/patch/handler/skip_quiz.py, skytemple_files/patch/patches.py
Adds a patch which lets the player discard the choice made by the personality quiz and choose the starter instead.
Seems to work on real hardware.
Extends overlay 13 size by 0x1000 bytes (should not be a problem since the size of this overlay still is below the size of some other menu overlays (e.g. 19)).
=> Adds a patch for an extra menu to choose the starter

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_dungeon_data/eu/patch_forbidden_floors.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_dungeon_data/na/patch_forbidden_floors.asm
ExtractDungeonData was overwriting 4 bytes of one of the hardcoded item lists.
With this bug, when ExtractHardcodedItemLists was applied after ExtractDungeonData lists were incorrectly extracted, which would ultimately cause a crash when accessing them.
=> Fix ExtractDungeonData patch

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_evo/common/patch_arm9.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_evo/common/patch_overlay16.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_evo/common/patch_overlay29.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_evo/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_evo/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_evo/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_evo/selector_arm9.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_evo/selector_overlay16.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_evo/selector_overlay29.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/common/types/file_types.py, skytemple_files/data/md_evo/__init__.py, skytemple_files/data/md_evo/handler.py, skytemple_files/data/md_evo/model.py, skytemple_files/data/md_evo/writer.py, skytemple_files/patch/handler/change_evo.py, skytemple_files/patch/patches.py
This patch changes how the game handles evolution. 
Creates two lists for each Pokémon: one that tells what it can evolve into and what Pokémon it has for children (important for eggs). This eliminates some particular cases the game normally handles to know that.
Also gives the possibility to set individual stat bonuses for each Pokémon when it evolved (stats bonuses are the ones from the Pokémon you evolved into).
=> Add a patch to change the game evolution system.

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_mappa/common/patch.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_mappa/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_mappa/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_mappa/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_mappa/selector_overlay29.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/externalize_mappa.py, skytemple_files/patch/patches.py
This patch currently only helps if the mappa file is too big to fit in RAM when loading it.
Also needs a LOT of tests to know if it doesn't break anything related to floors (spawn lists and attributes).
=> Add a patch to not entirely load the mappa file in RAM

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/common/fs_mappa_edited.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/common/patch_arm9.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/common/patch_overlay11.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/common/patch_overlay19.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/common/patch_overlay29.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/common/patch_overlay31.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/eu/constants.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/jp/constants.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/na/constants.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/selector_arm9.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/selector_overlay11.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/selector_overlay19.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/selector_overlay29.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/selector_overlay31.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/common/ppmdu_config/data.py, skytemple_files/common/ppmdu_config/xml_reader.py, skytemple_files/common/util.py, skytemple_files/data/dbg/xml_export_test.py, skytemple_files/data/md/model.py, skytemple_files/graphics/kao/model.py, skytemple_files/patch/arm_patcher.py, skytemple_files/patch/handler/expand_poke_list.py, skytemple_files/patch/patches.py
Pull requests #104, #105, #106 need to be merged before that
EXPERIMENTAL! Always make a backup before there is a 99.99% chance I forgot something that will break the game and changes can't be reverted
Tests are needed for almost everything in the game
If/When this works properly, extends the number of possible Pokémon slots from 600 entries with 2 possible forms to 2048 independent entries
Tries to maintain consistency upon applying the patch, this includes: 
[ASM]: 
- all the data access function for movesets, monster properties and portraits have been changed to work with the new system
- special monster personalities have been moved after the new entries
- special fixed floor monster IDs have been moved after the new entries IDs
- the code that spawned 2nd forms in even floors has …
=> Extend the Number of Pokémon entries

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/common/patch.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/na/offsets.asm
Fixes the assembly bug.
Patches that are dependent to this should also be re-applied.
=> Check for invalid waza data access

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/allow_unrecruitable_mons.py, skytemple_files/patch/patches.py
Adds a patch that allows recruiting pokémon that are hardcoded to be unrecruitable (The other 3 Deoxys forms and the regis).
=> Add AllowUnrecruitableMons patch

skytemple_files/patch/handler/move_shortcuts.py
The new version of MoveShortcuts displays the move list while holding L. It also prevents you from choosing linked or invalid moves.
Credits to @irdkwia!
MoveShortcuts now depends on the ExtraSpace patch.
=> Update MoveShortcuts to display the move list when holding L

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_tbbg/common/patch.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_tbbg/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_tbbg/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_tbbg/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_tbbg/selector_arm9.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/change_tbbg.py, skytemple_files/patch/patches.py
This patch changes the instructions that set the textbox background color to make textbox color editing easier.
Once applied, color will be at arm9:0x27800 [US], 0x27AF4 [EU], 0x27B60 [JP] in that format: R,G,B,A with 1 byte for each component (default color should be 0x20,0x20,0x20,0x90).
=> A patch to provide support for changing textbox bg color.

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/edit_extra_pokemon.py, skytemple_files/patch/patches.py
Adds a patch that un-hardcodes the way the game adds additional pokémon to the team when entering uncleared dungeons. This data will now be part of a table inside arm9.bin, making it possible to edit it with a hex editor.
=> Add EditExtraPokemon patch

skytemple_files/common/ppmdu_config/data.py, skytemple_files/common/ppmdu_config/xml_reader.py, skytemple_files/patch/arm_patcher.py, skytemple_files/patch/dbg/parameter_patches_test.py, skytemple_files/patch/dbg/parameters_test/asm_patches/header_stub_eu.asm, skytemple_files/patch/dbg/parameters_test/asm_patches/header_stub_na.asm, skytemple_files/patch/dbg/parameters_test/asm_patches/patch.asm, skytemple_files/patch/dbg/parameters_test/config.xml, skytemple_files/patch/dbg/parameters_test/patch.py, skytemple_files/patch/errors.py, skytemple_files/patch/handler/abstract.py, skytemple_files/patch/patches.py
This adds parameters for patches to the patches.
They can be used both in the Python handler and also in the armips source code (will be set as a label there).
See the example path in `skytemple_files/patch/dbg/parameters_test` for an example on how to use it.
The script `skytemple_files/patch/dbg/parameter_patches_test.py` runs a test apply of this dummy patch.
Here's the output when you run that script:
```
DEBUGGING PATCH PARAMETERS:
int_param <class 'int'> 1
int_param2 <class 'int'> 100
int_param3 <class 'int'> 1234
select_param <class 'str'> HELLO
string_param <class 'str'> World
ARMIPS CMDLINE:
['armips', '__main.asm', '-equ', 'int_param', '1', '-equ', 'int_param2', '100', '-equ', 'int_param3', '1234', '-equ', 'select_param', '"HELLO"', '-equ', 'string_param', '"World"']
ARMIPS …
```
=> Parameters for Patches

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/fix_memory_softlock.py, skytemple_files/patch/patches.py
Adds a patch that can help prevent the crashes that happen when the game runs out of memory when displaying sprites in cutscenes (this has been observed in roms that had custom sprites or had used the randomizer). Other glitches could happen instead, but it will probably stop the softlock.
The patch has no effect in the normal behaviour of the game, as long as it doesn't run out of memory the patch will not trigger.
In the only test I've done so far, the game went from a softlock to running with no apparent side effects after applying the patch.
=> Add FixMemorySoftlock patch

.gitignore
Since I can't seem to get env variables to work in my setup I just add the armips executable to _resources to apply patches in the dev version. It would be useful if said executable was in the gitignore to avoid having to add and remove it constantly.
=> Add armips to gitignore

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/common/patch.asm
Invalid pointer only checked 25% of the time because of a call to random(100) and branch to somewhere else if the result is below 75.
So literally 25% of crash on hardware.
...Fun.
#112
=> Actual fix for ChooseStarter patch

skytemple_files/patch/arm_patcher.py
I figured it crashed when applying any patch. After too much time spend looking at what went wrong, it was due to the copyright symbol, which isn't an ASCII character.
=> fixed issue linked to encoding

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/hardcoded/dbg/iq_groups_test.py, skytemple_files/hardcoded/iq.py, skytemple_files/patch/handler/compress_iq_data.py, skytemple_files/patch/patches.py
This code can be used to read/write the list of IQ skills in each group. Reads support the uncompressed (vanilla) format and the compressed (the one used by my CompressIQData patch) format. Writes only support the compressed format since writing data in the original format won't be necessary.
I still have to add the patch to SkyTemple, so I'll keep this as a draft until I do it (probably tomorrow).
Closes #165.
=> Support for IQ groups' skills

skytemple_files/patch/handler/fix_memory_softlock.py
Turns out there's 2 different places where the game allocates memory and they look almost the same. I didn't realize this when I created the FixMemorySoftlock patch (I even mixed up the offsets), so right now it doesn't work properly. This should fix it.
=> Fix FixMemorySoftlock patch

skytemple_files/_resources/patches/asm_patches/disarm_one_room_mh.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/disarm_one_room_mh.py, skytemple_files/patch/patches.py
Patch to de-Monster-House-ify the one-room Monster House default layout that appears when the dungeon generation algorithm fails. The speedrunners wanted this.
=> Add DisarmOneRoomMonsterHouses patch

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/common/patch_overlay29.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/na/offsets.asm
Excludes enemies gaining levels by exp. gain.
Enemies never update their exp. points value when they are created so its most of the time invalid.
=> Fix Exp Share patch

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/dungeon_interrupt/common/patch_overlay10.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/dungeon_interrupt/common/patch_overlay29.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/dungeon_interrupt/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/dungeon_interrupt/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/dungeon_interrupt/na/offsets.asm, skytemple_files/data/inter_d/model.py
Adds an option to continue the music after exiting the floor.
Needs testing.
=> Extend DungeonInterrupt to disable music fadeout

skytemple_files/patch/handler/move_growth.py, skytemple_files/patch/handler/stat_disp.py
Rename a couple of outdated paths that were causing an error when trying to apply the move growth or stat display patches.
=> Rename outdated paths

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/dynamic_bosses_everywhere.py, skytemple_files/patch/patches.py
Adds a patch that allows adding the special fixed pokémon entries used in Explorer Maze to any other fixed room (normally this would softlock the game).
Untested since I still haven't managed to fix my local SkyTemple installation.
=> Add DynamicBossesEverywhere patch

skytemple_files/hardcoded/fixed_floor.py
The second field in fixed room item data is the quantity. I renamed it so it can be edited.
See also https://github.com/SkyTemple/skytemple/pull/413
Looks like pmdsky-debug got updated too so I guess that goes in the PR as well. Hopefully it won't be an issue.
=> Allow editing fixed room item quantities

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/fs_waza_p/common/patch.asm, skytemple_files/dungeon_data/mappa_bin/floor_layout.py, skytemple_files/patch/handler/externalize_waza.py
For details see https://discord.com/channels/710190644152369162/975860892057088090/975915088676548660
There's been a report of a case where these PrintF calls cause a stack overflow, so I've removed them.
=> Fix potential stack overflow on ExternalizeWazaFile + Fix some floor densities being unsigned

skytemple_files/patch/handler/move_shortcuts.py
MoveShortcuts has been updated to prevent the player from passing turn by holding A+B while the move list is shown, which would cause a minor graphical glitch.
=> Update MoveShortcuts patch

skytemple_files/_resources/patches/asm_patches/adex_asm_mods/pitfall_trap_tweak/common/pitfall_ov29.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/pitfall_trap_tweak/common/pitfall_ov36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/pitfall_trap_tweak/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/pitfall_trap_tweak/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/pitfall_trap_tweak/selector_overlay29.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/pitfall_trap_tweak/selector_overlay36.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/pitfall_trap_tweak.py, skytemple_files/patch/patches.py
Adds a small ASM patch that slightly edits the behavior of Pitfall Traps. When the leader activates a Pitfall Trap in ascending dungeons, they now will descend a floor. Also, if the leader steps on a Pitfall Trap in 1F, they will restart 1F with a different seed.
I don't have a dev environment set up yet, so aside from having tried this out with patch packages, I'm unable to test if anything breaks while doing all of this.
=> Add PitfallTrapTweak patch

.github/workflows/check-pmdsky-debug.yml
The `--no-function-overlap` option for `resymgen check` was renamed to `--no-overlap`, so check-pmdsky-debug.yml needs to be updated accordingly.
I'm not sure when this submodule was last updated...I'm hoping there were no other breaking changes introduced since then.
=> Update pmdsky-debug to `c0fc599`

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/obj_table/eu/offsets.asm
I figured that the screen turned black except for dialogue in a cutscene of an hack I'm working on when applying this patch. After a bit of reverse-engineering, I found it was due to the padding overwriting some table that is used to check the ID of the of the background (in bg_list.dat) to load for the weather layer with 0xCC.
This patch fix some offset. The change itself was made by the original patch creator. (I got permission from them to upstream it).
It quickly tested it (as in, it didn't worked before, it work now. Didn't tried to add new object thought).
=> Fix obj_table breaking weather on EU rom

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/fix_nocash_saves.py, skytemple_files/patch/patches.py
Adds a patch that fixes saving in the No$GBA emulator, which allows playing the game without having to enable a cheat every time the emulator is opened.
I haven't been able to test this in SkyTemple since the latest dev version freezes when trying to load the ROM. The ASM patch itself is tested on both EU and US.
=> Add FixNo$GbaSaves patch

skytemple_files/common/ppmdu_config/script_data.py, skytemple_files/script/ssb/model.py
All enum arguments checks are exactly the same (save the const__by_id attribute in script_data), so replacing it with a single check using a dictionary mapping each enum to its script_data attribute should be better.
Would need to change rust implementation and rust interface files at: 
https://github.com/SkyTemple/skytemple-rust/blob/1852c5eb97bc6d177cc3d6f58fa338ff3514a48f/skytemple_rust/st_ssb.pyi#L52
https://github.com/SkyTemple/skytemple-rust/blob/1852c5eb97bc6d177cc3d6f58fa338ff3514a48f/skytemple_rust/st_ssb.pyi#L56
=> Suggestion: Make enum args checks more generic

skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/common/bold_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/common/bold_ov36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/selector_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/selector_overlay36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/common/sound_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/common/sound_ov36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/selector_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/selector_overlay36.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/bold_text.py, skytemple_files/patch/handler/change_text_sound.py, skytemple_files/patch/patches.py, skytemple_files/script/ssb/model.py
Adds two ASM patches that implement new text tags to be used in strings.
- BoldText adds the [BS] and [BR] text tags, where any text encased within them will be bolded.
- ChangeTextSound adds the [TS:X] (where X is an integer) and [TR] text tags. [TS:X] sets the textbox to use the Xth sound effect ID, while [TR] reverts the sound to its default.
=> Add BoldText and ChangeTextSound patches

skytemple_files/script/ssb/script_compiler.py
Interns (de-duplicates) strings during SSB compilation to save space (there are no ulterior motives).
This is completely untested since I couldn't be bothered to update and fix my development setup right now. I'm not deep enough into SSB internals to tell if this change could break anything.
=> Add string interning for const SSB strings

skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/completeteamcontrol.asm
Players are now prevented from changing team tactics during manual mode. For some reason, doing so completely destroys turn order and leadership status. 
(ignore the comment about this being a duplicate, I forgot to press the create pull request button last night)
=> Updated CTC to 1.2.4

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/anti_softlock.py, skytemple_files/patch/patches.py
Adds a patch that allows the user to press A+B+X+Y during cutscenes to unlock all locks at once. This can be used to fix many of the softlocks caused by changing the starters.
This patch could also be added as a default patch to the randomizer, since these kind of softlocks are common there.
=> Add AntiSoftlock patch

skytemple_files/patch/handler/extra_space.py
This updates ExtraSpace to the latest version, which adds support for static initialization. This allows other projects (like c-of-time) to run initialization code when the overlay is loaded.
I also fixed a bug that caused the overlay to be added as an empty file when applying the patch. Since `apply()` uses the overlay list to export the overlays to the temporary folder where the patch is applied, it skips overlay 36 (because the overlay list hasn't been patched yet at that point), which results in an empty file being written to the temporary folder. This means the overlay that was added to the rom with `rom.files.insert()` gets overwritten by the one on the temporary folder, resulting in an empty file.
This bug hasn't caused any problems until now, so it has gone unnoticed for a long …
=> Update ExtraSpace and fix how it's applied

skytemple_files/patch/handler/extra_space.py
ExtraSpace needs to be reapplyable so it can get updated to v0.2, which is needed to make CoT work.
This PR assumes #312 got merged, so that one should be merged first.
@theCapypara I'm guessing you'll make a hotfix release after #312 gets fixed, it would be good to include this as well.
=> Make ExtraSpace reapplyable

skytemple_files/patch/handler/move_shortcuts.py
MoveShortcuts 0.2.1 has a minor bug that prevents the player from passing their turn with A+B if their belly is less than 1.0. It only occurs if the leader pokémon struct is not aligned to 4 bytes, and probably only on real hardware and some emulators.
I don't think this can cause a crash, but it triggers a warning on No$GBA if they are enabled every time A+B is pressed.
The submodule commit includes the BetterEnemyEvolution patch too since #329 hasn't been merged yet.
=> Fix minor MoveShortcuts bug

skytemple_files/common/string_codec.py
Adds a method that allows checking if a string can be encoded using the PMD string codec. This is required for https://github.com/SkyTemple/skytemple-randomizer/pull/112.
I also modified the error message that triggers when trying to encode text that cannot be encoded to make it a bit more helpful.
=> Add method to check if a string can be encoded

skytemple_files/patch/handler/anti_softlock.py
How ironic. It could prevent others from softlocking, but not itself.
This fixes a bug that causes a softlock in real hardware and some emulators when A+B is pressed.
Since other PRs that update my patches repo haven't been merged yet (#329, #339), those updates are included here as well.
=> Fix softlock caused by AntiSoftlock patch

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/no_weather_stop.py, skytemple_files/patch/patches.py
Adds a patch that changes weather damage messages so they don't make the player stop running.
There's still a small delay when the message shows up, but it's no longer necessary to press the button again to keep running.
=> Add NoWeatherStop patch

skytemple_files/patch/handler/unused_dungeon_chance.py
Fixes a crash introduced in UnusedDungeonChance v0.1.1 that could happen when generating a wall maze room.
=> Fix UnusedDungeonChance crash

skytemple_files/dungeon_data/mappa_bin/_python_impl/monster.py, skytemple_files/dungeon_data/mappa_bin/mappa_xml.py, skytemple_files/dungeon_data/mappa_bin/protocol.py, test/skytemple_files_test/dungeon_data/mappa_bin/fixture.py, test/skytemple_files_test/dungeon_data/mappa_bin/fixtures/make_fixture.py, test/skytemple_files_test/dungeon_data/mappa_bin/mappa_bin_test.py
See also: https://github.com/SkyTemple/skytemple-rust/pull/62
SkyTemple UI changes pending. Issue for support for the Randomizer: https://github.com/SkyTemple/skytemple-randomizer/issues/139
=> Clarify monster spawn field names

skytemple_files/patch/handler/fix_memory_softlock.py
Updates the FixMemorySoftlock patch to a new version. The patch will now prevent crashes caused by the game running out of memory by replacing the sprite that can't be loaded with a default preloaded sprite. This should fix all the cutscene crashes caused by memory errors.
After this gets merged, the randomizer should be updated as well. The patch should probably applied by default.
=> Update FixMemorySoftlock to v2

skytemple_files/common/ppmdu_config/pmdsky_debug/extras.py
Adds some necessary JP "extra" symbols in arm9 and overlay11, as listed in https://github.com/SkyTemple/skytemple-files/issues/235.
=> Some extra JP symbols

skytemple_files/_resources/ppmdu_config/pmd2data.xml
@Laioxy @Adex-8x I can't add you as reviewers since you are not part of the SkyTemple GitHub organization. But can you have a look?
I tried to fix 
- https://github.com/SkyTemple/skytemple/issues/603
- https://github.com/SkyTemple/skytemple/issues/618
I tried this by moving the IDs for "Move Descriptions" and "IQ Skills Names" down/up one entry. This left a lot of overlap for the other string groups. I think the list is just in general still kind of wrong. What do you think?
=> Attempt to fix JP string blocks

skytemple_files/patch/handler/fix_memory_softlock.py
Minor update to FixMemorySoftlock. Should fix some of the crashes people are having while playing the randomizer.
=> Update FixMemorySoftlock to v2.1

skytemple_files/graphics/chara_wan/sheets.py
should fix https://github.com/SkyTemple/skytemple-files/issues/103
essentially, running quantize on an RGBA image can reduce the amount of colours in the palette even below the number passed into it (see https://github.com/python-pillow/Pillow/issues/5204 for further details). this poses a problem for glaceon specifically because one of its colours (0, 127, 159) is *really* close to the one defined as transparent.
since the actual transparent pixels have already been replaced with "transparent" pixels at this point, we can just convert it to RGB before running quantize to avoid this
=> fix glaceon transparency bug

skytemple_files/graphics/chara_wan/sheets.py
this can potentially loop infinitely because `transparent[3] - 1` is always 254. i think this was meant to use the previous colour's blue value, not its alpha value
=> fix backup transparent colours

skytemple_files/graphics/chara_wan/sheets.py
if the previous piece is already flipped, then hflip should be set to false on the new piece to flip it again
=> fix double flipping metaframepieces

skytemple_files/_resources/patches/asm_patches/adex_asm_mods/add_key_check/common/key_ov29.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/add_key_check/common/key_ov36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/add_key_check/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/add_key_check/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/add_key_check/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/add_key_check/selector_overlay29.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/add_key_check/selector_overlay36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_portrait/common/portrait_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_portrait/common/portrait_ov29.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_portrait/common/portrait_ov36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_portrait/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_portrait/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_portrait/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_portrait/selector_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_portrait/selector_overlay29.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_portrait/selector_overlay36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/display_script_var/common/var_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/display_script_var/common/var_ov36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/display_script_var/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/display_script_var/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/display_script_var/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/display_script_var/selector_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/display_script_var/selector_overlay36.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/patch/handler/add_key_check.py, skytemple_files/patch/handler/change_portrait.py, skytemple_files/patch/handler/display_script_var.py, skytemple_files/patch/patches.py
Adds three ASM patches:
- `AddKeyCheck`
- Disallows a party member from using a Key (Item ID 182) in the dungeon menu unless they're standing right below a Key Door.
- `ChangePortraitMidText`
- Implements the text tag `[FACE:X]`, where "X" is the new portrait emotion ID to change the currently-loaded portrait to. This works in ground and dungeon mode, and will default to the default (FACE_NORMAL) portrait if the specified portrait emotion cannot be found.
- ~~@AlliterativeAlias are you proud of me~~
- `DisplayScriptVariable`
- Implements the text tag `[var:x:y]`, where "x" is a script variable ID and "y" (optional; will default to 0 if not present) is an index. The text tag will be replaced with the value of the specified script variable.
=> Add various ASM patches

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/dungeon_interrupt/common/patch_arm9.asm
Adds a validity and a fixed bounds check to a loop in `DungeonInterrupt`, which caused crashes on hardware while applied alongside `ExternalizeWazaFile`.
Closes https://github.com/SkyTemple/skytemple-files/issues/463.
=> Fix DungeonInterrupt loop

skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsEU.asm, skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsJP.asm, skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsUS.asm, skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/completeteamcontrol.asm, skytemple_files/patch/handler/complete_team_control.py
When using Complete Team Control, if you attempted to use an Orb with an ally who wasn't originally the leader, the game would still recalculate the potential targets surrounding them. This has the noticeable impact of an ally using an Orb in an unintended direction from where they're currently facing. 
This should fix that behavior to make it so allies won't recalculate their targets.
=> Fix Orb oversight with Complete Team Control

skytemple_files/_resources/ppmdu_config/pmd2scriptdata.xml
The effect is the first parameter, and the duration is the second parameter. They were the wrong way around (according to the wiki)
=> Swap effect and duration parameters for back_SetEffect and back2_SetEffect

skytemple_files/_resources/ppmdu_config/pmd2data.xml
This PR aims to revise the string blocks that are currently defined for the three Explorers of Sky versions (NA/EU/JP). The text linking was done via spreadsheet and added to the directory for future reference as `linked-eos-strs.csv`.
This new set of blocks have been compared with the previous version to ensure the regions being used by the UI (https://github.com/SkyTemple/skytemple/blob/e90441e56af1e0523254efe3498161b8981ac771/skytemple/core/string_provider.py#L32-L59) are named the same - there are some changes which I believe should be applied however:
* IQ Skills Names: **(9957, 10025) -> (9956, 10025)** 
* ID 9957 should be included as the equivalent JP string is "[M:D1]かしこさ なし" meaning "No IQ"
* Trap Names: **(13504, 13530) -> (13504, 13529)** 
* ID 13530 should not be included as …
=> Consolidate string blocks across NA/EU/JP versions

skytemple_files/hardcoded/symbols/manual/structs.py
Allows viewing the internal size of sprites on the symbols screen. Requires pmdsky-debug-py to be updated to include the latest pmdsky-debug changes (PR: https://github.com/UsernameFodder/pmdsky-debug/pull/264)
=> Add monster_sprite_data_entry struct

skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/common/ppmdu_config/pmdsky_debug/extras.py, skytemple_files/hardcoded/guest_pokemon.py, skytemple_files/patch/handler/edit_guest_pokemon.py, skytemple_files/patch/patches.py
Fixes the currently bugged EditExtraPokemon patch and renames it to EditGuestPokemon.
Other related PRs:
- https://github.com/SkyTemple/skytemple/pull/780
- https://github.com/SkyTemple/skytemple-randomizer/pull/215
=> Rename and fix EditGuestPokemon patch

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_poke_list/common/patch_arm9.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_poke_list/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_poke_list/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_poke_list/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/sprite_size/common/patch_arm9.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/sprite_size/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/sprite_size/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/sprite_size/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/sprite_size/selector_arm9.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/common/sprite_util.py, skytemple_files/patch/handler/expand_poke_list.py, skytemple_files/patch/handler/sprite_size.py, skytemple_files/patch/patches.py
Sprite Size part of the ExpandPokeList patch is independent an can be extracted to another patch.
This changes ExpandPokeList so that it depends on that new patch, SpriteSizeInMonsterData.
=> Move Sprite Size elements to another patch

skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/common/bold_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/common/bold_ov36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/bold_text/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/common/sound_arm9.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/common/sound_ov36.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/adex_asm_mods/change_text_sound/na/offsets.asm, skytemple_files/patch/handler/change_text_sound.py
Some minor improvements to two patches:
- `BoldText`: When characters' widths are read while bold text is active, then it will be increased by 1 to prevent characters from bleeding into one another.
- `ChangeTextSound`: Added an optional second parameter to the text tag specifying the volume. If the text tag is used without a volume parameter, it defaults to 256.
=> Minor improvements to BoldText and ChangeTextSound

skytemple_files/common/sprite_util.py
Seems that in fact attack animations are handed in a dedicated VRAM area by the game
=> Remove Attack Sprite in calculation

skytemple_files/common/sprite_util.py, skytemple_files/graphics/chara_wan/model.py, skytemple_files/graphics/chara_wan/writer.py
Add a function to compute max VRAM blocks in chara_wan model, which is now used for sprite size checks
=> Use Chara Wan model to compute VRAM Size

skytemple_files/graphics/chara_wan/model.py, skytemple_files/graphics/chara_wan/sheets.py, skytemple_files/graphics/chara_wan/split_merge.py, skytemple_files/graphics/chara_wan/wan_utils.py
- Fix sprite with missing chunks in frame
- This is due to the Y offset being misinterpreted in chunks (Y offset is actually a signed 10-bit integer)
- Slightly improve sprite file size reduction
- Reuses the same algorithm that merges chunks with same image data, which can slightly improve file size especially if two frames are similar in the sprite
=> Sprite fixes and improvements

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_poke_list/common/patch_arm9.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_poke_list/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_poke_list/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_poke_list/na/offsets.asm
Fixes a problem with Unown species using a hardcoded check with its own String ID
=> Fix ExpandPokeList patch Unown strings

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_portrait/common/patch.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_portrait/eu/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_portrait/jp/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_portrait/na/offsets.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/expand_portrait/selector_arm9.asm, skytemple_files/_resources/ppmdu_config/pmd2data.xml, skytemple_files/graphics/kao/_model.py, skytemple_files/graphics/kao/handler.py, skytemple_files/graphics/kao/protocol.py, skytemple_files/patch/handler/expand_portrait.py, skytemple_files/patch/patches.py
Reuploads that patch
> Adds a patch to expand the portrait structure allocated by the game by 8 bytes, which is enough to contain all possible cases of compressed portraits (worst case is an uncompressed ATNPX container which would be 807 bytes, while the expanded structure can contain up to 808 bytes).
Adds a property for Kao Image import to specify that limit.
See:
Skytemple/skytemple#803
Skytemple/skytemple-rust#123
=> Reupload portrait limit patch

skytemple_files/patch/handler/add_key_check.py, skytemple_files/patch/handler/better_enemy_evolution.py, skytemple_files/patch/handler/bold_text.py, skytemple_files/patch/handler/change_portrait.py, skytemple_files/patch/handler/change_text_sound.py, skytemple_files/patch/handler/display_script_var.py, skytemple_files/patch/handler/pitfall_trap_tweak.py
Oops, I forgot to make my patches' descriptions translatable, so I tweaked them (plus one of Frostbyte's).
Is this enough, or is there more that's needed for the translation stuff to just work? I'm pretty unfamiliar with it.
=> Add description translatability for some patches

skytemple_files/common/version_util.py
Originally reported at: https://discord.com/channels/710190644152369162/1301663321036161117
SkyTemple hangs if it cannot connect to release.skytemple.org
=> Add timeout to version and banner checks

skytemple_files/common/exceptions/outdated_patch_dependency.py, skytemple_files/patch/handler/abstract.py
Allows ASM patches to raise an exception if any of their dependencies is outdated and needs to be reapplied.
Needed for #556.
=> Add OutdatedPatchDependency exception

skytemple_files/_resources/ppmdu_config/pmd2data.xml
TeamStatsPain fails to apply in SkyTemple 1.8.4, as the filepath for overlay 10 was invalid. This change remedies this issue.
=> TeamStatsPain filepath correction

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/extract_bar_list/eu/patch.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/extract_bar_list/jp/patch.asm, skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/extract_bar_list/na/patch.asm
Causes read to invalid range for items after ID 0x200 (e.g. 0x100-0x300 for items 0x200-0x400)
=> Fix Extract Bar List patch invalid cache read

skytemple_files/common/util.py
- Adds functionality to delete files and folders from the ROM provided a path
- Adds functionality to create files and folders in the ROM in the filesystem's root folder (e.g., `create_folder_in_rom(rom, 'CUSTOM')` will now work)
- Fixes creating folders in a folderless directory, which would previously assign a folder `firstID` of -2 and render the ROM unable to be saved 
- Fixed a smol typo in an error message
=> File/folder deletion support + file/folder root creation support

tools/export_ssb.py
Adds [Para's script dump tool](https://gist.github.com/theCapypara/455bb2c7dfc385ae808cc36cd263ad89), which can be used to dump all scripts in a ROM to ExplorerScript. Tested working on a vanilla EU ROM.
I had to change the encoding of the output to ensure that all scripts could be dumped. Everything else was left untouched.
=> Add script dump tool
