SkyTemple/skytemple-files

.gitmodules
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/actor_and_level_loader.py

Related to pull request PsyCommando/pmd2_asm_mods#3.
Fix compatibility issues with the new version when it will be approved.
It should only be merged after the pull request above is closed and merged.
Also, "_resources/patches/asm_patches/pmd2_asm_mods" should be updated to the reference the new commit.

Preparing support for the new version of the patch

---

skytemple_files/_resources/ppmdu_config/pmd2scriptdata.xml
skytemple_files/hardcoded/dbg/dungeons_test.py
skytemple_files/hardcoded/dungeons.py

- Renaming map_id to level_id for world map markers.
- Fix the EU level lists table in the ppmdu script data file.

Fix world map component

---

skytemple_files/common/types/file_types.py
skytemple_files/compression/rle_nibble/__init__.py
skytemple_files/compression/rle_nibble/compressor.py
skytemple_files/compression/rle_nibble/decompressor.py
skytemple_files/compression/rle_nibble/handler.py
skytemple_files/graphics/fonts/__init__.py
skytemple_files/graphics/fonts/abstract.py
skytemple_files/graphics/fonts/banner_font/__init__.py
skytemple_files/graphics/fonts/banner_font/dbg/export_test.py
skytemple_files/graphics/fonts/banner_font/dbg/import_test.py
skytemple_files/graphics/fonts/banner_font/handler.py
skytemple_files/graphics/fonts/banner_font/model.py
skytemple_files/graphics/fonts/banner_font/writer.py
skytemple_files/graphics/fonts/font_dat/__init__.py
skytemple_files/graphics/fonts/font_dat/model.py

Adds basic support for editing banner fonts (dungeons, chapters and episodes banners):
- open/edit/write
- import/export.
Also adds a RLE compressor/decompressor to compress font data from those files.
Fixes other font implementations to work with the UI.

Add support for editing banner fonts

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/graphics/kao/handler.py

Adds the pointer to the memory allocation table the game uses at runtime.

Add pointers to the game memory allocation table

---

skytemple_files/common/tiled_image.py

Improves performance of the function that converts a PIL Image to tilemaps (used when importing backgrounds).

Increase performance when converting an image to tilemaps

---

skytemple_files/common/types/file_types.py
skytemple_files/data/tbl_talk/__init__.py
skytemple_files/data/tbl_talk/dbg/__init__.py
skytemple_files/data/tbl_talk/dbg/export_test.py
skytemple_files/data/tbl_talk/handler.py
skytemple_files/data/tbl_talk/model.py
skytemple_files/data/tbl_talk/writer.py

Related to #36.
Adds a model, handler and writer for editing TblTalk files.

Add support for editing TblTalk file

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/_resources/ppmdu_config/pmd2dungeondata.xml
skytemple_files/common/types/file_types.py
skytemple_files/graphics/colvec/__init__.py
skytemple_files/graphics/colvec/dbg/export_test.py
skytemple_files/graphics/colvec/dbg/import_test.py
skytemple_files/graphics/colvec/handler.py
skytemple_files/graphics/colvec/model.py
skytemple_files/graphics/colvec/writer.py

Adds support for editing the colvec file (in dungeon.bin): 
- handler/model/writer
- import/export
This file contains the color maps used to alter color palettes depending on the weather.

Add support for editing dungeon Color Maps.

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/common/types/file_types.py
skytemple_files/dungeon_data/fixed_bin/model.py
skytemple_files/graphics/chr/__init__.py
skytemple_files/graphics/chr/dbg/export_test.py
skytemple_files/graphics/chr/dbg/import_test.py
skytemple_files/graphics/chr/handler.py
skytemple_files/graphics/chr/model.py
skytemple_files/graphics/chr/writer.py
skytemple_files/graphics/pal/model.py
skytemple_files/hardcoded/cart_removed.py

Adds model/handler/writer for editing chr files (used for upper screen window styles).
Adds module to edit the hardcoded cartridge removed image in arm9.

Add support for chr files + cartridge removed image

---

skytemple_files/graphics/chara_wan/model.py
skytemple_files/graphics/chara_wan/sheets.py

Also added function to check for anim reqs

Fix anim_name_map index out of range

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml

Adds useful constants for the debugger.

Add constants for debug flags functions.

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fix_evolution/patch.asm
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/fix_evolution.py
skytemple_files/patch/patches.py

Fixes the glitch when trying to evolve a pokémon that has 10 characters in their name.

Add a patch to fix the evolution glitch (NA)

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/eu/patch_arm9.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/eu/patch_overlay29.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/na/patch_arm9.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/na/patch_overlay29.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/selector_arm9.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/selector_overlay29.asm
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/exp_share.py
skytemple_files/patch/patches.py

- Adds a patch to implement experience share (EU and NA)

Adds the exp. share patch

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/eu/patch_arm9.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/exp_share/na/patch_arm9.asm
skytemple_files/patch/handler/exp_share.py
skytemple_files/patch/handler/fix_evolution.py

Improve the patch to add the possibility to change that percentage instead of a fixed 100%.

Set the percentage of exp. shared to non-party members

---

.vscode/settings.json
skytemple_files/graphics/kao/model.py
skytemple_files/graphics/kao/writer.py

Deleting portraits wasn't possible before.
This PR is linked to https://github.com/SkyTemple/skytemple/pull/214
Resolves https://github.com/SkyTemple/skytemple/issues/106

Delete portraits in response of UI

---

skytemple_files/graphics/chara_wan/handler.py
skytemple_files/graphics/chara_wan/sheets.py

Reference to https://github.com/SkyTemple/skytemple/issues/167
This new method allows saving the sheets in a zip archive. I was able to do it on my local version of skytemple. The next step will be to add the button to the application.
Here is the generated archive:
[bulbasaur.zip](https://github.com/SkyTemple/skytemple-files/files/6065362/bulbasaur.zip)

Add method to import/export sheets with zip

---

skytemple_files/dungeon_data/fixed_bin/model.py

I noticed the description for a couple of fixed room tiles was outdated and updated it.

Update fixed room tiles text

---

skytemple_files/_resources/patches/asm_patches/cipnit_asm_mods/common/offsetsUS.asm

Put an EU value in the US region on accident pwease fowgive me maestwoke o~o

o noo i made an oopsie woopsie

---

skytemple_files/data/md/model.py
skytemple_files/data/md/writer.py
skytemple_files/data/monster_xml.py

Update evolution parameter 2 according to what it determines.

Update Monster Attributes

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_sp_code/eu/patch.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_sp_code/na/patch.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_sp_code/selector_overlay11.asm
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/extract_sp_code.py
skytemple_files/patch/patches.py

Adds a patch to write custom ground engine special process code, in the same way as move and item effects.

Special Process Code patch

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/common/patch.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/na/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/selector_arm9.asm
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/externalize_waza.py
skytemple_files/patch/patches.py

This is exactly the same as #102, just moved the changes to another branch in my fork to keep my master branch updated with the upstream.

Add a patch to not entirely load the waza_p file in RAM

---

skytemple_files/patch/arm_patcher.py

Does two things :
- fix the the error display. Before this fix, displaying the error in case of failure failed, as ``f`` is a file rather than the function
- Ensure the permission are correctly set after copying the file (the folder where Nix store it's data is marked as read-only).

enhancment in the arm patcher for packaging

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/common/fs_mappa_edited.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_mappa/common/patch.asm

Fixed an invalid pointer access with guaranteed items.
Also modifies ExpandPokeList as it uses that.

Fixed a bug in fs_mappa patch

---

skytemple_files/patch/handler/move_shortcuts.py

Otherwise depends_on will never work as intended.

Just saying it's a dependant patch

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/common/patch.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/fs_waza_p/na/offsets.asm

Try to fix lag caused by ExternalizeWazaFile patch.
Don't forget to apply the ExpandPokeList patch again after ExternalizeWazaFile.
If you have some information about where the lag/potential glitches are, please tell me.

Try to fix lag (attempt 1/1000000)

---

skytemple_files/common/util.py
skytemple_files/data/data_cd/armips_importer.py
skytemple_files/patch/arm_patcher.py

Basically the same thing as https://github.com/SkyTemple/skytemple-files/pull/128 , but for special process.

added support for read-only skytemple storage for special process patch

---

skytemple_files/graphics/bgp/model.py

The game uses tile 0 to clear backgrounds.
Caused that background glitch in EoD.

Fix BGP model: tile 0 must be blank

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/hardcoded/dbg/guest_pokemon_test.py
skytemple_files/hardcoded/guest_pokemon.py

Related to #28. Adds support to read/write guest pokémon data (requires the EditExtraPokemon patch to be applied).
Feel free to point out mistakes or make suggestions, this is the first python script I've written that has more than 10 lines.

Guest pokémon support

---

requirements.txt
setup.py
skytemple_files/common/dungeon_floor_generator/__init__.py
skytemple_files/common/dungeon_floor_generator/dbg/test_generator.py
skytemple_files/common/dungeon_floor_generator/generator.py

Using irdkwia's dungeon generator.
Backend part for SkyTemple/skytemple#301

Dungeon Generator / Dungeon Preview

---

skytemple_files/hardcoded/guest_pokemon.py

Updated unk2 value in guest pokémon data and removed an unnecessary parameter.

Minor refactor

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/common/patch.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/choose_starter/na/offsets.asm
skytemple_files/patch/handler/choose_starter.py

Attempt to fix hardware issues with ChooseStarter patch

---

skytemple_files/hardcoded/default_starters.py

Fix Special Episode PCs entries

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_ff_prop/common/patch.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_ff_prop/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_ff_prop/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_ff_prop/na/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/change_ff_prop/selector_overlay29.asm
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/change_ff_prop.py
skytemple_files/patch/patches.py

This patch removes hard-coded checks for fixed floor properties and replaces some with new properties.

Add ChangeFixedFloorProperties patch

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/hardcoded/dbg/iq_test.py
skytemple_files/hardcoded/dungeon_misc.py
skytemple_files/hardcoded/iq.py

Closes #127 and closes #18
Also see skytemple/skytemple#330

IQ data editing

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/hardcoded/iq.py

Closes #168
I have the feeling the data isn't correct yet? I'm not sure where I messed up, can you check?
See also skytemple/skytemple#331

Closes #168: IQ Skill restrictions

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/extract_sp_code/eu/patch.asm
skytemple_files/patch/handler/move_growth.py

ExtractSPCode EU fix + MoveGrowth clarification

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/common/patch_overlay29.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/na/offsets.asm

This should fix crashes when Female Castform and Cherrim are transforming.

Fix Expand Pokémon List

---

skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/common/patch_overlay10.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/na/offsets.asm
skytemple_files/_resources/patches/asm_patches/irdkwia_asm_mods/expand_poke_list/selector_overlay10.asm
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/data/anim/__init__.py
skytemple_files/data/anim/handler.py
skytemple_files/data/anim/model.py
skytemple_files/data/anim/writer.py

- Adds Handler/Model/Writer for file "BALANCE/anim.bin" created by the patch ExtractAnimData.
- Fixes move animation related stuff with ExpandPokeList.

Add support for editing animation tables + Fix ExpandPokeList

---

skytemple_files/export_maps.py
skytemple_files/graphics/wan_wat/dbg/export_sprites_test.py
skytemple_files/graphics/wan_wat/model.py

Require https://github.com/SkyTemple/skytemple-rust/pull/6

Ability to import image as static ground object

---

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/obj_table/common/patch.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/obj_table/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/obj_table/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/obj_table/na/offsets.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/obj_table/selector_overlay11.asm
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/common/ppmdu_config/rom_data/loader.py
skytemple_files/common/types/file_types.py
skytemple_files/list/object/__init__.py
skytemple_files/list/object/handler.py
skytemple_files/list/object/model.py
skytemple_files/list/object/writer.py
skytemple_files/patch/handler/obj_table.py
skytemple_files/patch/patches.py

- Adds a patch to extract the object table.
- Add handlers for read/writing into this object table.

Support for editing the script object table

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml

It seems there is a trap description at the end of the list of trap name

fixed trap name position in EU

---

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/appraise_all/common/patch.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/appraise_all/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/appraise_all/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/appraise_all/na/offsets.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/appraise_all/selector_overlay25.asm
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/appraise_all.py
skytemple_files/patch/patches.py

Adds a patch enabling a new option to appraise all boxes at once from Xatu's box appraisal menu (NA/EU versions).
Example of how it works: https://youtu.be/Lrs26tPNwU4
Thanks to @Adex-8x for testing it!

Appraise all boxes at once patch

---

skytemple_files/common/util.py
skytemple_files/patch/arm_patcher.py
skytemple_files/patch/patches.py

Implements my suggestion to ensure that trying to patch overlay 36 when ExtraSpace isn't applied results in an error.

Suggestion for #312

---

skytemple_files/common/util.py
skytemple_files/patch/arm_patcher.py
skytemple_files/patch/handler/extra_space.py
skytemple_files/patch/patches.py

Fix ExtraSpace corruption

---

skytemple_files/data/item_p/_model.py

Descriptions updated to match the UI changes in https://github.com/SkyTemple/skytemple/pull/504.

Update item AI flags description

---

skytemple_files/dungeon_data/fixed_bin/dbg/draw_test.py
skytemple_files/export_maps.py
skytemple_files/graphics/wan_wat/dbg/dungeon_bg_sprites_test.py
skytemple_files/graphics/wan_wat/dbg/export_sprites_test.py
skytemple_files/graphics/wan_wat/model.py

Add compatibility for change with https://github.com/SkyTemple/skytemple-rust/pull/43

pmd_wan: handle update to 5.1.1

---

skytemple_files/hardcoded/dungeons.py

Adds the recently documented "random movement chance" dungeon restriction.
See also https://github.com/SkyTemple/skytemple/pull/512.

Add random movement chance to dungeon restrictions

---

skytemple_files/_resources/ppmdu_config/pmd2dungeondata.xml

Closes #415, closes #412, closes #414

Closes #415: Fix dungeon.bin for JP ROM

---

skytemple_files/_resources/ppmdu_config/skytemple.xml

Mark JP ROM as supported

---

skytemple_files/patch/handler/extra_space.py

Updates the `end_asm_mods` submodule to include https://github.com/End45/EoS-asm-hacks/pull/7.

Update ExtraSpace patch

---

skytemple_files/_resources/ppmdu_config/pmd2scriptdata.xml

Updated many of the parameters named "unk", using parameter names from the SkyTemple wiki: https://wiki.skytemple.org/index.php/List_of_Opcodes

Added names for unk parameters from wiki

---

.github/workflows/build-test-publish.yml
pyproject.toml
requirements.txt
test/skytemple_files_test/script/ssb/export_import_explorerscript_test.py

Also updates ExplorerScript to include a small edge-case bugfix for a bug that was uncovered in the process.

Re-enable ROM tests, add ExplorerScript ROM test

---

skytemple_files/_resources/ppmdu_config/pmd2scriptdata.xml
skytemple_files/script/ssb/script_compiler.py

Fixes skytemple/skytemple-ssb-debugger#122 and an additional user report.

Fix back_SetBackEffect and WaitBack2Effect opcodes

---

skytemple_files/_resources/ppmdu_config/pmd2scriptdata.xml

All of the parameters here should now be fully consistent with https://wiki.skytemple.org/index.php/List_of_Opcodes

More updates to parameters from wiki

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/negative_enemy_density.py
skytemple_files/patch/patches.py

Continuation from https://github.com/SkyTemple/skytemple-files/pull/462#issuecomment-1872531275
Adds a new patch that makes negative enemy densities work as intended

Add NegativeEnemyDensity patch

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/remove_body_size_check.py
skytemple_files/patch/patches.py

Adds a patch that removes the total body size check the game performs before the player tries to enter a dungeon.

Add RemoveBodySizeCheck patch

---

pyproject.toml
requirements.txt
skytemple_files/common/ppmdu_config/pmdsky_debug/extras.py
skytemple_files/hardcoded/menus.py
skytemple_files/hardcoded/text_speed.py

Some symbols were renamed, this still needs to be fixed, and other SkyTemple sources must be checked as well.

bump pmdsky-debug

---

skytemple_files/common/ppmdu_config/script_data.py
skytemple_files/script/ssb/constants.py
skytemple_files/script/ssb/model.py

:warning: This might break with the actor/level list loader patch due to the way the data of the ROM is linked into there right now I need to check this more closely before merging

Additional pre-caching of static data

---

.gitmodules
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/common/ppmdu_config/pmdsky_debug/extras.py
skytemple_files/dungeon_data/fixed_bin/README.rst
skytemple_files/dungeon_data/mappa_bin/README.rst
skytemple_files/dungeon_data/mappa_g_bin/README.rst
skytemple_files/patch/handler/allow_unrecruitable_mons.py
skytemple_files/patch/handler/anti_softlock.py
skytemple_files/patch/handler/better_enemy_evolution.py
skytemple_files/patch/handler/complete_team_control.py
skytemple_files/patch/handler/compress_iq_data.py
skytemple_files/patch/handler/disable_tips.py
skytemple_files/patch/handler/dynamic_bosses_everywhere.py
skytemple_files/patch/handler/edit_extra_pokemon.py
skytemple_files/patch/handler/extra_space.py
skytemple_files/patch/handler/fix_memory_softlock.py
skytemple_files/patch/handler/fix_nocash_saves.py
skytemple_files/patch/handler/move_shortcuts.py
skytemple_files/patch/handler/negative_enemy_density.py
skytemple_files/patch/handler/no_weather_stop.py
skytemple_files/patch/handler/remove_body_size_check.py
skytemple_files/patch/handler/same_type_partner.py
skytemple_files/patch/handler/unused_dungeon_chance.py

- Updates my username everywhere on the repo (I'll open more PRs for the other repos)
- Updates the submodule for my ASM patches, it's now named `frost_asm_mods` and has a new upstream URL: https://github.com/Frostbyte0x70/EoS-asm-patches
Other related PRs:
- https://github.com/SkyTemple/skytemple/pull/771
- https://github.com/SkyTemple/skytemple-randomizer/pull/212
- https://github.com/SkyTemple/skytemple-ssb-debugger/pull/136

Username update

---

skytemple_files/common/ppmdu_config/rom_data/loader.py
skytemple_files/common/ppmdu_config/script_data.py
skytemple_files/script/ssb/constants.py

Replaces string operations in `map_back` with a pre-populated map of all constants.

Single hash table lookup for `map_back`

---

skytemple_files/common/ppmdu_config/script_data.py

I tried making it less verbose and ended up making it more verbose :thinking: - but at least the caching is now also only updated when changed

Further optimize new Pmd2ScriptData

---

skytemple_files/common/ppmdu_config/script_data.py

This reverts commit 5c3ff2aa5486db0905d6d3bfcdef62484ad1cc7d, PR #529
Closes skytemple/skytemple#796
The logic didn't actually invalidate the cache...

Revert "Further optimize new Pmd2ScriptData (#529)"

---

skytemple_files/graphics/chara_wan/split_merge.py

These functions help reducing animation groups in the wan file to a specified list
One function gives the list of non-empty groups for a wan file, which can be used to reduce another wan to the same set of animations

Create ReduceWan and ActiveGroupsWan helper functions

---

skytemple_files/_resources/patches/asm_patches/chesyon_asm_mods/team_stats_pain/common/pain_ov10.asm
skytemple_files/_resources/patches/asm_patches/chesyon_asm_mods/team_stats_pain/common/pain_ov36.asm
skytemple_files/_resources/patches/asm_patches/chesyon_asm_mods/team_stats_pain/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/chesyon_asm_mods/team_stats_pain/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/chesyon_asm_mods/team_stats_pain/na/offsets.asm
skytemple_files/_resources/patches/asm_patches/chesyon_asm_mods/team_stats_pain/selector_overlay10.asm
skytemple_files/_resources/patches/asm_patches/chesyon_asm_mods/team_stats_pain/selector_overlay36.asm
skytemple_files/_resources/ppmdu_config/pmd2data.xml
skytemple_files/patch/handler/team_stats_pain.py
skytemple_files/patch/patches.py

Added the TeamStatsPain patch from the Discord's #community-patches channel. This patches changes a team member's portrait in the Team Stats menu to pain when in critical condition, if such a portrait exists.
(gonna hope i didn't forget anything hhhhhh)

Added TeamStatsPain patch

---

skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/push_allies/common/patch_overlay29.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/push_allies/common/patch_overlay36.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/push_allies/eu/offsets.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/push_allies/jp/offsets.asm
skytemple_files/_resources/patches/asm_patches/anonymous_asm_mods/push_allies/na/offsets.asm

Items will now be picked up by the leader after swapping places, instead of passing over

Change behavior Push Allies patch

---

skytemple_files/_resources/ppmdu_config/pmd2data.xml

Correct Yes/No for Luminous Spring being in Chimeco Assembly String category.

Correct Luminous Spring Strings

---

skytemple_files/graphics/effect_wan/README.rst
skytemple_files/graphics/effect_wan/handler.py
skytemple_files/graphics/effect_wan/model.py
skytemple_files/graphics/effect_wan/sheets.py
skytemple_files/graphics/wan_wat/handler.py

Parses wan files in /EFFECT/effect.bin, with some exceptions (see the README) which contains move VFX and cutscene VFX.
Only reads and exports. Import not supported.

effect_wan support

---

skytemple_files/common/exceptions/outdated_patch_dependency.py
skytemple_files/patch/handler/fix_nocash_saves.py

Continuation of https://github.com/SkyTemple/skytemple-files/pull/556, which got automatically closed when I tried to push additional commits for some reason.
@Chesyon

FixNo$GbaSaves 1.0.0

---

pyproject.toml
skytemple_files/graphics/bpl/_model.py

Fixes https://github.com/SkyTemple/skytemple/issues/821
This finally makes all map background palette animations actually look correct, for the first time ever!
Rust implementation: https://github.com/SkyTemple/skytemple-rust/pull/137

fix BPL palette animation

---

skytemple_files/_resources/ppmdu_config/pmd2spritedata.xml
skytemple_files/graphics/chara_wan/handler.py
skytemple_files/graphics/chara_wan/sheets.py

Fixes default animation labeling for grovyle.
Adds the option to delete anims from a wan file.

Chara wan fix

---

skytemple_files/script/ssb/script_compiler.py
test/skytemple_files_test/script/ssb/jump_test.py

Closes https://github.com/SkyTemple/ExplorerScript/issues/61

Fix offset consistency after Ssb compilation
